### ISSUE TITLE
Don't work :(

### ISSUE THREAD

**Issue by Robin38219733** [zvovov/whatsapp-web#1]
When i try to start the Script i got the following Output:
Press Ctrl+C again to exit.

This error is Yellow.

The Chromedriver ist installed and working.

**Comment by zvovov** [comment]
Hey, I'm away for a couple weeks. Will look into it as soon as I get some
time.

On 11 Feb 2017 4:59 p.m., "Robin38219733" <notifications@github.com> wrote:

When i try to start the Script i got the following Output:
Press Ctrl+C again to exit.

This error is Yellow.

The Chromedriver ist installed and working.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/zvovov/whatsapp-web/issues/1>, or mute the thread

**Comment by zvovov** [comment]
Tested and it's working fine.
Check if the path to chromedriver in chat.py is correctly defined.
