### ISSUE TITLE
After login on whatsapp gets an error 'Unable to locate element'

### ISSUE THREAD

**Issue by cibertuti** [zvovov/whatsapp-web#13]
Hi, I install the script on my MacOs  High Sierra, when I run the script and scan the qr code, when I see the chat list press 'y' at the 'question phone connected?' at the console and gets the error:

'Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="main"]/header//div[contains(@class, "chat-main")]"}
  (Session info: chrome=64.0.3282.140)
  (Driver info: chromedriver=2.35.528157 (4429ca2590d6988c0745c24c8858745aaaec01ef),platform=Mac OS X 10.13.3 x86_64)

        Chromedriver Error. Read the above error (if any), then
        Check if installed chromedriver version is compatible with installed Chrome vesion.'

Any ideas?
Thank you

**Comment by nzurita** [comment]
+1, similar issue here in Ubuntu 16.04. As Firefox has released new versions, do you plan to release a new version compatible with Firefox?

**Comment by VanityR** [comment]
+1, Same issue

**Comment by PiPauwels** [comment]
This issue isn't Chromedriver related, it's due to some code changes in the webversion of WhatsApp itself. I'll have a patch ready today. I must add that I am a brand new Github user, so am I supposed to create a fork if I want to patch a project of which I am not the author?

**Comment by VanityR** [comment]
Unfortunately in the same boat - new user myself.

I assumed that it was due to DOM changes as I was trying out the xpath
selectors manually and obviously they had no match.

I was in the process of manually specifying them(to which end I managed to
send messages but not receive them - but I was just fiddling during down
time, plus I'm not familiar with python).

Sorry I can't be of any further help! Best of luck :)

On 22 Feb 2018 15:40, "PiPauwels" <notifications@github.com> wrote:

This issue isn't Chromedriver related, it's due to some code changes in the
webversion of WhatsApp itself. I'll have a patch ready today. I must add
that I am a brand new Github user, so am I supposed to create a fork if I
want to patch a project of which I am not the author?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/zvovov/whatsapp-web/issues/13#issuecomment-367720769>,
or mute the thread

**Comment by PiPauwels** [comment]
Update: the most recent version of my fork is now able to receive messages, as well as send them: https://github.com/PiPauwels/whatsapp-web  

Since the receiving mechanism was based on an attribute "data-id", which has been omitted during recent DOM-changes, the new mechanism is now based on the name of te sender and the contents of the message (if both differ from the previous last printed message, new messages are printed to the screen). I've also incorporated the timestamp and sender name present in the current DOM, which is -IMHO- more useful than printing the group name in front of every message.

There remains one problem, which has something to do with another reported issue: https://github.com/zvovov/whatsapp-web/issues/4. At random times (not yet sure what causes the exception) that same exception is thrown, after which receiving messages is nog longer possible, but sending them keeps working. I will investigate this up next.

Planning on incorporating images & emoji once I get that bug out of the way.

**Comment by zvovov** [comment]
Should be fixed now.
@PiPauwels brilliant work!
