### ISSUE TITLE
Visual interface is required for read the QR code?

### ISSUE THREAD

**Issue by luigisalas** [zvovov/whatsapp-web#29]
Hi, thi code can used without a visual interface in linux? only accessing via ssh? The register process, read the QR, etc. Or is necessary a visual interface for read the QR for example?

I want try it in my server, but I only have ssh access.

**Comment by zvovov** [comment]
Doing the authentication via ssh is not possible right now because this
program relies on Google Chrome for QR code authentication and other tasks.
It is possible, in theory, to have a headless browser replace Google
Chrome. But currently, you would need access to your linux server's desktop
environment/GUI to use this there.

**Comment by luigisalas** [comment]
Thanks for the answer.
