### ISSUE TITLE
Insights for new features

### ISSUE THREAD

**Issue by paolospane** [zvovov/whatsapp-web#6]
Dear,
I would like to share with u an Insights:
* Is It possible read the whatsapp db?
* If the answer at the previous question is no. Is it possible redirect the chat (send and receive in a external DB)?
* When can we "download/upload" attach?
* Exist an catch function that is the trigger for external code?(when i receive the messages i would like to exec some external program and send automatic answer).

Best Regards,
Paolo

**Comment by zvovov** [comment]
Is It possible read the whatsapp db? **Possible? Yes. Does it work now? No.**
If the answer at the previous question is no. Is it possible redirect the chat (send and receive in a external DB)? ** You can try saving your console logs to save chats. **
When can we "download/upload" attach? **Would need to find a way to share non-text data between console and Chrome**
Exist an catch function that is the trigger for external code?(when i receive the messages i would like to exec some external program and send automatic answer).  ** You can add a listener for an additional keyword that does that.**

**Comment by tomasi-o** [comment]
Is ist possible to run whatsapp-cli w/o the Chrome Browser?

**Comment by zvovov** [comment]
In theory, yes. Replacing chromdriver with a headless browser will work it work without Chrome browser. Chrome also started supporting headless mode recently, if I recall correctly. 
The only thing to really work on would be a way to authenticate using the QR code. If you find a way to transfer the QR code from the whatsapp web website to the console (and repeatedly poll the site, because the QR code changes automatically every 10 seconds or so) then there's no need of any GUI browser.

**Comment by thatskriptkid** [comment]
@zvovov Hi! Can your library subscribe to user presence status?

**Comment by zvovov** [comment]
No, it cannot yet. But it's a good idea.

**Comment by Camps94** [comment]
Heyyy amazing project! Many thanks! I'm trying to send images too! Do you know I could implement this feature? Do you think it's possible to load the script in a machine in pythoneverywhere that could send a message periodically or it'snt possible because it has to verify your phone everytime except when you run it in your terminal I mean..

Sorry if my questions are too basic :( 

Best regards

**Comment by nakiom** [comment]
Is there any way to send a message to unsaved contacts?

**Comment by zvovov** [comment]
@nakiom If you've messaged the contact at least once, you should be able to type their number and chat with them. Not sure if the code searches within the current chats, or all contacts. If it searches in the current chats, you should be able to search for a number and chat

**Comment by metin02oktay** [comment]
@zvovov On hosting server we can use "VNC server" once time,  please add "send file" feature. I can write python script :(

**Comment by metin02oktay** [comment]
I'll use it to send large files with base64 ...
Could you help me with this?

**Comment by zvovov** [comment]
@metin02oktay Please raise a PR with your code and let's take it from there
